In [1]:
from pathlib import Path

import autochem as ac
import automech
import automol
import more_itertools as mit
import numpy as np
from project_utilities import p_
from protomech import mess

T_range = (300, 1200)
T_vals = (600, 700, 800, 900, 1000, 1100, 1200)
P_vals = (0.1, 1, 10, 100)
T_drop = (300, 400)  # Drop low-T rates for fit
A_fill = 1e-20
compare = False

stoich = "C5H7"
clear_nodes = []
clear_edges = []

# stoich = "C5H7O2"
# clear_nodes = []  # was clearing: ["C5H6O(645)z+OH(4)", "CPND2(626)+OH(4)"]
# clear_edges = []

# stoich = "C5H9"
# clear_nodes = []
# clear_edges = []

# stoich = "C5H9O"
# clear_nodes = []
# clear_edges = []

stoich = "C5H9O2"
clear_nodes = []
clear_edges = [
    # Well-skipping:
    ("C5H8O(833)+OH(4)", "C5H8O(829)rs+OH(4)")
]

# stoich = "C5H11O"  # suspicious -- doesn't seem to compare well with theory
# clear_nodes = []
# clear_edges = []

# stoich = "C5H11O2"
# clear_nodes = []
# clear_edges = []

tag = "Z_mess_v0"
root_path = Path("../..")
stoich_path = Path(stoich)

In [2]:
mech = automech.io.read(p_.stereo_mechanism(tag, "json", p_.data(root_path)))
mech.reactions = automech.reaction.select_pes(mech.reactions, stoich)
mech = automech.without_unused_species(mech)

In [3]:
mess_inp = stoich_path / "mess.inp"
surf = mess.surf.from_mess_input(mess_inp)

In [4]:
from importlib import reload
from protomech.mess import surf as m_surf_

reload(m_surf_)

mess_out = stoich_path / "rate.out"
surf = m_surf_.with_mess_output_rates(surf, mess_out=mess_out)
surf = m_surf_.absorb_fake_nodes(surf)
mess.net.display(surf, mech=mech, height="1000px")

In [5]:
import autochem as c

node_key = 3
for rate_key in mess.surf.rate_keys(surf):
    if rate_key[0] == node_key:
        print(rate_key)
        branch_frac = surf.branching_fractions[rate_key]
        print(branch_frac(T=T_vals, P=P_vals))
        display(ac.rate.data.display(branch_frac, plot_type="simple"))

(3, 6)
[[5.92391304e-09 2.22010870e-08 4.15760870e-08 4.78260870e-08]
 [3.67217281e-09 2.43964422e-08 7.66200762e-08 1.15374841e-07]
 [1.60264901e-09 1.79470199e-08 9.73509934e-08 2.20529801e-07]
 [5.78947368e-10 9.84962406e-09 9.02255639e-08 3.31203008e-07]
 [2.13501144e-10 4.69107551e-09 6.49885584e-08 3.93592677e-07]
 [9.55752212e-11 2.24188791e-09 4.04129794e-08 3.80530973e-07]
 [6.43564356e-11 1.25742574e-09 2.46534653e-08 3.15841584e-07]]


alt.Chart(...)

(3, 7)
[[6.30434783e-11 6.30434783e-09 2.98913043e-07 2.44565217e-06]
 [7.58576874e-11 4.18043202e-09 2.13468869e-07 3.25285896e-06]
 [1.48344371e-10 4.26490066e-09 1.58940397e-07 3.33112583e-06]
 [5.11278195e-10 7.06766917e-09 1.47368421e-07 3.07518797e-06]
 [2.12814645e-09 1.73226545e-08 1.83524027e-07 2.90617849e-06]
 [7.18289086e-09 4.42477876e-08 2.87610619e-07 3.00884956e-06]
 [1.80198020e-08 9.51485149e-08 4.71287129e-07 3.35643564e-06]]


alt.Chart(...)

(3, 8)
[[6.30434783e-11 6.30434783e-09 2.98913043e-07 2.44565217e-06]
 [7.54764930e-11 4.18043202e-09 2.13468869e-07 3.25285896e-06]
 [1.48344371e-10 4.26490066e-09 1.58940397e-07 3.33112583e-06]
 [5.11278195e-10 7.06766917e-09 1.47368421e-07 3.07518797e-06]
 [2.12814645e-09 1.73226545e-08 1.83524027e-07 2.90617849e-06]
 [7.18289086e-09 4.42477876e-08 2.87610619e-07 3.00884956e-06]
 [1.80198020e-08 9.51485149e-08 4.71287129e-07 3.35643564e-06]]


alt.Chart(...)

(3, 9)
[[1.52717391e-10 4.48369565e-10            nan            nan]
 [1.51207116e-10 6.81067344e-10 5.20965693e-10            nan]
 [1.22516556e-10 1.03973510e-09 1.58278146e-09 6.17218543e-10]
 [1.01879699e-10 1.22180451e-09 3.37593985e-09 2.24812030e-09]
 [9.47368421e-11 1.25629291e-09 5.62929062e-09 6.22425629e-09]
 [1.03982301e-10 1.24778761e-09 7.93510324e-09 1.40117994e-08]
 [1.27722772e-10 1.23762376e-09 9.80198020e-09 2.65346535e-08]]


alt.Chart(...)

(3, 10)
[[1.52717391e-10 4.48369565e-10            nan            nan]
 [1.51207116e-10 6.81067344e-10 5.18424396e-10            nan]
 [1.22516556e-10 1.03973510e-09 1.58278146e-09 6.17218543e-10]
 [1.01879699e-10 1.22180451e-09 3.37593985e-09 2.24812030e-09]
 [9.47368421e-11 1.25629291e-09 5.62929062e-09 6.22425629e-09]
 [1.03982301e-10 1.24778761e-09 7.93510324e-09 1.40117994e-08]
 [1.27722772e-10 1.23762376e-09 9.80198020e-09 2.65346535e-08]]


alt.Chart(...)

(3, 11)
[[1.36956522e-11 1.60054348e-11 1.77173913e-11 1.12228261e-11]
 [1.35959339e-10 2.08386277e-10 2.23634053e-10 1.80432020e-10]
 [5.91390728e-10 1.36423841e-09 1.75496689e-09 1.60927152e-09]
 [1.48872180e-09 5.07518797e-09 8.72180451e-09 9.09774436e-09]
 [2.81464531e-09 1.24256293e-08 2.97482838e-08 3.72997712e-08]
 [4.80825959e-09 2.31563422e-08 7.44837758e-08 1.17404130e-07]
 [8.44554455e-09 3.76237624e-08 1.46534653e-07 2.97029703e-07]]


alt.Chart(...)

(3, 12)
[[1.10326087e-12            nan 1.08695652e-12 9.72826087e-13]
 [1.29606099e-11 2.18551461e-11 2.47776366e-11 2.04574333e-11]
 [6.06622517e-11 1.60264901e-10 2.31788079e-10 2.21854305e-10]
 [1.54511278e-10 6.20300752e-10 1.28195489e-09 1.45864662e-09]
 [2.88329519e-10 1.51945080e-09 4.59954233e-09 6.63615561e-09]
 [4.91150442e-10 2.83185841e-09 1.16666667e-08 2.25663717e-08]
 [8.47524752e-10 4.54455446e-09 2.26732673e-08 5.95049505e-08]]


alt.Chart(...)

(3, 13)
[[5.73369565e-12 7.17391304e-12 6.16847826e-12 5.19021739e-12]
 [4.37102922e-11 7.86531131e-11 9.21219822e-11 7.50952986e-11]
 [1.48344371e-10 4.09271523e-10 6.44370861e-10 6.30463576e-10]
 [3.15789474e-10 1.19924812e-09 2.73308271e-09 3.36090226e-09]
 [5.56064073e-10 2.42562929e-09 7.68878719e-09 1.26544622e-08]
 [1.01622419e-09 4.18879056e-09 1.60766962e-08 3.58407080e-08]
 [1.88118812e-09 6.65346535e-09 2.73267327e-08 7.94059406e-08]]


alt.Chart(...)

(3, 14)
[[5.73369565e-12            nan 8.09782609e-12 5.19021739e-12]
 [4.37102922e-11 7.86531131e-11 9.23761118e-11 7.50952986e-11]
 [1.48344371e-10 4.09271523e-10 6.44370861e-10 6.30463576e-10]
 [3.15789474e-10 1.19924812e-09 2.73308271e-09 3.36090226e-09]
 [5.56064073e-10 2.42562929e-09 7.68878719e-09 1.26544622e-08]
 [1.01622419e-09 4.18879056e-09 1.60766962e-08 3.58407080e-08]
 [1.88118812e-09 6.65346535e-09 2.73267327e-08 7.94059406e-08]]


alt.Chart(...)

(3, 16)
[[           nan            nan            nan            nan]
 [1.84243964e-13            nan 7.05209657e-13            nan]
 [2.21854305e-13 9.60264901e-13 1.21192053e-12 1.82781457e-13]
 [5.52631579e-13 2.77819549e-12 5.78947368e-12 2.98496241e-12]
 [1.63386728e-12 6.95652174e-12 1.90617849e-11 1.79862700e-11]
 [4.82300885e-12 1.75516224e-11 5.30973451e-11 7.47787611e-11]
 [1.35643564e-11 4.53465347e-11 1.34653465e-10 2.42574257e-10]]


alt.Chart(...)

(3, 17)
[[2.06521739e-14            nan            nan            nan]
 [7.68742058e-14            nan            nan 1.12960610e-14]
 [2.21192053e-13 1.00662252e-12 1.25827815e-12 2.05960265e-13]
 [5.41353383e-13 2.78571429e-12 5.75187970e-12 2.97744361e-12]
 [1.62013730e-12 6.95652174e-12 1.90160183e-11 1.79862700e-11]
 [4.80825959e-12 1.75516224e-11 5.30973451e-11 7.49262537e-11]
 [1.35643564e-11 4.53465347e-11 1.35643564e-10 2.42574257e-10]]


alt.Chart(...)

(3, 2)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


alt.Chart(...)

(3, 5)
[[1.49728261e-09 1.49728261e-09 1.49728261e-09 1.49728261e-09]
 [1.34688691e-08 1.34688691e-08 1.34688691e-08 1.34688691e-08]
 [7.68211921e-08 7.68211921e-08 7.68211921e-08 7.68211921e-08]
 [3.19172932e-07 3.19172932e-07 3.19172932e-07 3.19172932e-07]
 [1.05263158e-06 1.05263158e-06 1.05263158e-06 1.05263158e-06]
 [2.92035398e-06 2.92035398e-06 2.92035398e-06 2.92035398e-06]
 [7.00990099e-06 7.00990099e-06 7.00990099e-06 7.00990099e-06]]


alt.Chart(...)

(3, 23)
[[           nan            nan            nan            nan]
 [           nan            nan            nan            nan]
 [           nan            nan            nan            nan]
 [           nan            nan            nan            nan]
 [           nan            nan 2.92906178e-08 8.39816934e-08]
 [           nan            nan 1.78466077e-08 6.16519174e-10]
 [2.95049505e-08 3.05940594e-08 1.82178218e-08 2.77227723e-08]]


alt.Chart(...)

(3, 24)
[[4.53804348e-06            nan 4.72826087e-06            nan]
 [1.28335451e-05 1.27064803e-05 1.26429479e-05 9.39008895e-06]
 [2.31788079e-05 2.31788079e-05 2.31788079e-05 2.04635762e-05]
 [3.79699248e-05 3.79699248e-05 3.79699248e-05 3.60902256e-05]
 [5.83524027e-05 5.83524027e-05 5.83524027e-05 5.67505721e-05]
 [8.46607670e-05 8.46607670e-05 8.45132743e-05 8.30383481e-05]
 [1.16831683e-04 1.16831683e-04 1.16831683e-04 1.14851485e-04]]


alt.Chart(...)

(3, 25)
[[           nan 7.74456522e-10            nan            nan]
 [           nan 7.31893266e-11            nan            nan]
 [3.09933775e-10 1.83443709e-10 7.74834437e-11            nan]
 [9.32330827e-10 7.18045113e-10 2.33458647e-10 1.97744361e-11]
 [2.35697941e-09 2.05491991e-09 9.63386728e-10 1.48283753e-10]
 [5.29498525e-09 4.94100295e-09 3.08259587e-09 7.13864307e-10]
 [1.07920792e-08 1.03960396e-08 7.94059406e-09 2.67326733e-09]]


alt.Chart(...)

(3, 26)
[[2.40489130e-13            nan            nan            nan]
 [1.49936468e-13            nan            nan            nan]
 [8.74172185e-13 2.03973510e-13            nan            nan]
 [3.12781955e-12 2.83458647e-12            nan 5.37593985e-14]
 [1.87643021e-11 1.77574371e-11 1.05720824e-11 2.02745995e-12]
 [9.18879056e-11 8.83480826e-11 6.51917404e-11 1.84365782e-11]
 [3.59405941e-10 3.51485149e-10 2.94059406e-10 1.18811881e-10]]


alt.Chart(...)

(3, 27)
[[           nan            nan            nan            nan]
 [           nan 2.40152478e-12            nan            nan]
 [5.66887417e-11 3.80132450e-11            nan            nan]
 [3.24812030e-10 2.63909774e-10 9.58646617e-11 7.81954887e-12]
 [1.38901602e-09 1.24027460e-09 6.47597254e-10 9.61098398e-11]
 [4.80825959e-09 4.52802360e-09 3.05309735e-09 7.31563422e-10]
 [1.40594059e-08 1.35643564e-08 1.07920792e-08 3.82178218e-09]]


alt.Chart(...)

(3, 28)
[[4.42934783e-08 2.79891304e-08 8.77717391e-09 1.28260870e-09]
 [1.25285896e-07 1.03811944e-07 5.20965693e-08 1.13468869e-08]
 [2.83443709e-07 2.65562914e-07 1.86092715e-07 6.20529801e-08]
 [5.63909774e-07 5.52631579e-07 4.69924812e-07 2.29699248e-07]
 [1.02288330e-06 1.01830664e-06 9.51945080e-07 6.24713959e-07]
 [1.74041298e-06 1.74041298e-06 1.68141593e-06 1.34513274e-06]
 [2.77227723e-06 2.77227723e-06 2.74257426e-06 2.43564356e-06]]


alt.Chart(...)

(3, 30)
[[9.26630435e-06 9.26630435e-06 9.26630435e-06 9.26630435e-06]
 [2.43964422e-05 2.43964422e-05 2.43964422e-05 2.43964422e-05]
 [5.55629139e-05 5.55629139e-05 5.55629139e-05 5.55629139e-05]
 [1.12781955e-04 1.12781955e-04 1.12781955e-04 1.12781955e-04]
 [2.09153318e-04 2.09153318e-04 2.09153318e-04 2.09153318e-04]
 [3.61356932e-04 3.61356932e-04 3.61356932e-04 3.61356932e-04]
 [5.84158416e-04 5.84158416e-04 5.84158416e-04 5.84158416e-04]]


alt.Chart(...)

(3, 31)
[[4.13043478e-12 8.75000000e-13 1.06521739e-13 8.85869565e-15]
 [1.52477764e-10 5.19695044e-11 8.58958069e-12 8.46251588e-13]
 [2.02649007e-09 1.03973510e-09 2.51655629e-10 3.05298013e-11]
 [1.39849624e-08 9.66165414e-09 3.43984962e-09 5.45112782e-10]
 [6.43020595e-08 5.28604119e-08 2.63157895e-08 5.69794050e-09]
 [2.25663717e-07 2.03539823e-07 1.30088496e-07 3.86430678e-08]
 [6.48514851e-07 6.12871287e-07 4.63366337e-07 1.84158416e-07]]


alt.Chart(...)